import type { MenuItem } from './types';

export const menuData: Omit<MenuItem, 'imageUrl' | 'imageHint'>[] = [
  {
    id: 1,
    name: 'Bruschetta',
    description: 'Toasted baguette slices topped with fresh tomatoes, garlic, basil, and a drizzle of balsamic glaze.',
    price: 9.99,
    category: 'Appetizers',
    imageId: 'bruschetta',
  },
  {
    id: 2,
    name: 'Spinach & Artichoke Dip',
    description: 'A warm, creamy blend of spinach, artichoke hearts, and cheese, served with crispy tortilla chips.',
    price: 11.50,
    category: 'Appetizers',
    imageId: 'spinach-dip',
  },
  {
    id: 3,
    name: 'Golden Calamari',
    description: 'Lightly breaded and fried calamari rings served with a zesty marinara sauce and lemon wedges.',
    price: 13.00,
    category: 'Appetizers',
    imageId: 'calamari',
  },
  {
    id: 4,
    name: 'Grilled Salmon',
    description: 'A perfectly grilled salmon fillet seasoned with herbs, served with roasted asparagus and lemon butter sauce.',
    price: 24.00,
    category: 'Entrees',
    imageId: 'grilled-salmon',
  },
  {
    id: 5,
    name: 'Pasta Primavera',
    description: 'Fettuccine tossed with a medley of fresh spring vegetables in a light and savory garlic-herb sauce.',
    price: 18.50,
    category: 'Entrees',
    imageId: 'pasta-primavera',
  },
  {
    id: 6,
    name: 'Classic Steak Frites',
    description: 'A juicy 8oz sirloin steak cooked to your liking, served with a generous portion of crispy golden fries.',
    price: 28.99,
    category: 'Entrees',
    imageId: 'steak-frites',
  },
  {
    id: 7,
    name: 'Chicken Parmesan',
    description: 'Tender chicken breast, breaded and fried, then baked with marinara and mozzarella. Served over spaghetti.',
    price: 21.00,
    category: 'Entrees',
    imageId: 'chicken-parm',
  },
  {
    id: 8,
    name: 'Tiramisu',
    description: 'Layers of coffee-soaked ladyfingers and creamy mascarpone, dusted with cocoa powder.',
    price: 8.50,
    category: 'Desserts',
    imageId: 'tiramisu',
  },
  {
    id: 9,
    name: 'Molten Chocolate Lava Cake',
    description: 'A decadent warm chocolate cake with a gooey molten center, served a la mode with vanilla bean ice cream.',
    price: 9.00,
    category: 'Desserts',
    imageId: 'lava-cake',
  },
  {
    id: 10,
    name: 'New York Cheesecake',
    description: 'A rich and creamy cheesecake with a graham cracker crust, topped with fresh strawberry coulis.',
    price: 8.00,
    category: 'Desserts',
    imageId: 'cheesecake',
  },
];
